version: '3.6'

services:
    go:
        container_name: go-feeder
        image: appto-go
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - '5500'
        ports:
            - '8050:5500'
        restart: unless-stopped
        networks:
            - devom
        env_file:
            - .env

networks:
    devom:
        name: devom_net
