version: '3.6'

services:
    go:
        container_name: devom-feeder
        image: appto-go
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - '5500'
        ports:
            - '8050:5500'
        restart: unless-stopped
        networks:
            - appto
        env_file:
            - .env

networks:
    appto:
        name: appto_net
